# Generated by Django 4.0.6 on 2022-07-25 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('parkmovement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkmovement',
            name='validate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customervehicle'),
        ),
    ]
