# Generated by Django 4.0.6 on 2022-07-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('parkmovement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customervehicle'),
        ),
    ]
